Repository kids-first/kf-api-fhir-service, pull requests merged in 2021-05, with the labels that each got.

#105 ⬆️ Upgrade to 2021.02.R05
  Dockerfile
  README.md
  docker-compose.yml
  docs/images/401-not-auth.png
  docs/images/auth0-signin.png
  docs/images/smile-cdr-success.png
  scripts/update_smilecdr.sh
Labels: documentation, feature

#106 Feature/add caring
  Jenkinsfile
  Jenkinsfile_CARING
Labels: devops

#110 🏷 Release 0.4.0
  CHANGELOG.md
Labels: release
